app = "fabrix-central"

[build]
  dockerfile = "Dockerfile"

[[services]]
  protocol = "tcp"
  internal_port = 4000

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [[services.ports]]
    port = 80
    handlers = ["http"]

  [services.http_checks]
    interval = "15s"
    grace_period = "30s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "5s"

[env]
  PORT = "4000"
  NODE_ENV = "production"
  DATABASE_URL = "postgresql://neondb_owner:npg_MKpo28GmUrbx@ep-empty-rain-ale5i0yo-pooler.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
  REDIS_URL = "rediss://default:gQAAAAAAAbMKAAIgcDJlNzdkNzI4ZmQ3MjY0MmE2OTdhZjRhYzFlZmRiODA0Yg@loved-tortoise-111370.upstash.io:6379"
  JWT_ACCESS_SECRET = "jS+kTyoYnO0xGEIQh+F6yMmlTxPBc9G3HTIjgFv3PutDsiAGtL8NQrdiJlfR03rQ"
  JWT_REFRESH_SECRET = "3kdBUO+TDCb8dsXgIL5UoNjpLzRlC71V089bwRsdI5lsc+pg5Ly6KzxtNUT92BM9"
  CORS_ORIGINS = "https://fabrix.sbs,https://www.fabrix.sbs,https://api.fabrix.sbs"
  AGENT_JWT_ACCESS_SECRET = "7LwLBcL2XQ9NpYP5dkW0GUDsl2sfiRzPZkmsxCmDahxmpfXUnYD5Na87evlwDYKC"
  AGENT_JWT_REFRESH_SECRET = "1QvUh9yV0HdKRzLRf+3vDeLunrCEjQcicZqH4vX+Wap5Hpj4huHjaTKVo8CR2lEW"
  AGENT_JWT_ACCESS_TTL = "15m"
  AGENT_JWT_REFRESH_TTL = "30d"
  AGENT_LOGIN_BASE_URL = "https://fabrix.sbs/agent/auth"
  APP_URL = "https://fabrix.sbs"
  API_URL = "https://api.fabrix.sbs"
  NEXAPAY_API_KEY = "nxp_developer_aa603022e4a1083809825a91_7e7a8be1"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
